name: Release Go Package
on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      github.event.ref_type == 'tag' &&
      github.ref == concat('refs/tags/', github.event.ref) &&
      github.ref == 'refs/tags/' * 'refs/heads/main/*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build and publish package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref }}
          path: ./
